import type { ResponseLanguageCode } from "../response-language";

type ResearchLanguageCopy = {
  caveat: string;
  evidenceLabel: string;
  found: (topic: string, count: number) => string;
  limitationLabel: string;
  missing: (topic: string) => string;
  noProviderIssues: string;
  onchainLabel: string;
  onchainStatus: (status: string, toolCount: number) => string;
  providerIssues: (count: number) => string;
  providers: (value: string) => string;
  providersLabel: string;
  recommendation: string;
  retryRecommendation: string;
  socialLabel: string;
  socialStatus: (status: string) => string;
  synthesisFailed: (reason?: string) => string;
  title: string;
};

export function getResearchLanguageCopy(
  code: ResponseLanguageCode
): ResearchLanguageCopy {
  return researchLanguageCopy[code];
}

export function localizeSignalStatus(
  code: ResponseLanguageCode,
  status: string
) {
  const labels = signalStatusCopy[code];

  return labels[status as keyof typeof labels] ?? status;
}

export function localizeResearchHeadings(
  markdown: string,
  code: ResponseLanguageCode
) {
  const labels = researchSectionLabels[code];

  return markdown.replace(
    /^(#{1,6})[ \t]+(Read|Evidence|Candidates|Limits|Conclusion|Recommendation|Caveats?)[ \t]*$/gim,
    (_, level: string, rawLabel: string) => {
      const key = rawLabel.toLowerCase().startsWith("caveat")
        ? "caveat"
        : rawLabel.toLowerCase() as keyof ResearchSectionLabels;

      return `${level} ${labels[key]}`;
    }
  );
}

type ResearchSectionLabels = {
  candidates: string;
  caveat: string;
  conclusion: string;
  evidence: string;
  limits: string;
  read: string;
  recommendation: string;
};

const researchSectionLabels: Record<
  ResponseLanguageCode,
  ResearchSectionLabels
> = {
  ar: { read: "القراءة", evidence: "الأدلة", candidates: "المرشحون", limits: "القيود", conclusion: "الخلاصة", recommendation: "التوصية", caveat: "قيد" },
  de: { read: "Einordnung", evidence: "Evidenz", candidates: "Kandidaten", limits: "Grenzen", conclusion: "Fazit", recommendation: "Empfehlung", caveat: "Einschränkung" },
  el: { read: "Ανάγνωση", evidence: "Τεκμήρια", candidates: "Υποψήφια", limits: "Περιορισμοί", conclusion: "Συμπέρασμα", recommendation: "Σύσταση", caveat: "Περιορισμός" },
  en: { read: "Read", evidence: "Evidence", candidates: "Candidates", limits: "Limits", conclusion: "Conclusion", recommendation: "Recommendation", caveat: "Caveat" },
  es: { read: "Lectura", evidence: "Evidencia", candidates: "Candidatos", limits: "Límites", conclusion: "Conclusión", recommendation: "Recomendación", caveat: "Limitación" },
  fr: { read: "Lecture", evidence: "Preuves", candidates: "Candidats", limits: "Limites", conclusion: "Conclusion", recommendation: "Recommandation", caveat: "Limitation" },
  he: { read: "קריאה", evidence: "ראיות", candidates: "מועמדים", limits: "מגבלות", conclusion: "מסקנה", recommendation: "המלצה", caveat: "מגבלה" },
  hi: { read: "विश्लेषण", evidence: "साक्ष्य", candidates: "उम्मीदवार", limits: "सीमाएँ", conclusion: "निष्कर्ष", recommendation: "सुझाव", caveat: "सीमा" },
  id: { read: "Pembacaan", evidence: "Bukti", candidates: "Kandidat", limits: "Keterbatasan", conclusion: "Kesimpulan", recommendation: "Rekomendasi", caveat: "Keterbatasan" },
  it: { read: "Lettura", evidence: "Evidenze", candidates: "Candidati", limits: "Limiti", conclusion: "Conclusione", recommendation: "Raccomandazione", caveat: "Limitazione" },
  ja: { read: "読み取り", evidence: "根拠", candidates: "候補", limits: "制限", conclusion: "結論", recommendation: "推奨事項", caveat: "制限" },
  ko: { read: "해석", evidence: "근거", candidates: "후보", limits: "한계", conclusion: "결론", recommendation: "권고", caveat: "제한" },
  nl: { read: "Analyse", evidence: "Bewijs", candidates: "Kandidaten", limits: "Beperkingen", conclusion: "Conclusie", recommendation: "Aanbeveling", caveat: "Beperking" },
  pt: { read: "Leitura", evidence: "Evidências", candidates: "Candidatos", limits: "Limites", conclusion: "Conclusão", recommendation: "Recomendação", caveat: "Limitação" },
  ru: { read: "Анализ", evidence: "Доказательства", candidates: "Кандидаты", limits: "Ограничения", conclusion: "Вывод", recommendation: "Рекомендация", caveat: "Ограничение" },
  th: { read: "การอ่าน", evidence: "หลักฐาน", candidates: "รายการคัดเลือก", limits: "ข้อจำกัด", conclusion: "สรุป", recommendation: "คำแนะนำ", caveat: "ข้อจำกัด" },
  tr: { read: "Okuma", evidence: "Kanıt", candidates: "Adaylar", limits: "Sınırlamalar", conclusion: "Sonuç", recommendation: "Öneri", caveat: "Sınırlama" },
  vi: { read: "Diễn giải", evidence: "Bằng chứng", candidates: "Ứng viên", limits: "Giới hạn", conclusion: "Kết luận", recommendation: "Khuyến nghị", caveat: "Giới hạn" },
  zh: { read: "解读", evidence: "证据", candidates: "候选项", limits: "限制", conclusion: "结论", recommendation: "建议", caveat: "限制" },
};

const signalStatusCopy: Record<
  ResponseLanguageCode,
  Record<"failed" | "partial" | "skipped" | "success", string>
> = {
  ar: { failed: "فشل", partial: "جزئي", skipped: "تم التخطي", success: "ناجح" },
  de: { failed: "fehlgeschlagen", partial: "teilweise", skipped: "übersprungen", success: "erfolgreich" },
  el: { failed: "απέτυχε", partial: "μερικό", skipped: "παραλείφθηκε", success: "επιτυχές" },
  en: { failed: "failed", partial: "partial", skipped: "skipped", success: "successful" },
  es: { failed: "fallido", partial: "parcial", skipped: "omitido", success: "correcto" },
  fr: { failed: "échec", partial: "partiel", skipped: "ignoré", success: "réussi" },
  he: { failed: "נכשל", partial: "חלקי", skipped: "דולג", success: "הצליח" },
  hi: { failed: "विफल", partial: "आंशिक", skipped: "छोड़ा गया", success: "सफल" },
  id: { failed: "gagal", partial: "sebagian", skipped: "dilewati", success: "berhasil" },
  it: { failed: "fallito", partial: "parziale", skipped: "saltato", success: "riuscito" },
  ja: { failed: "失敗", partial: "一部完了", skipped: "スキップ", success: "成功" },
  ko: { failed: "실패", partial: "부분 완료", skipped: "건너뜀", success: "성공" },
  nl: { failed: "mislukt", partial: "gedeeltelijk", skipped: "overgeslagen", success: "geslaagd" },
  pt: { failed: "falhou", partial: "parcial", skipped: "ignorado", success: "bem-sucedido" },
  ru: { failed: "ошибка", partial: "частично", skipped: "пропущено", success: "успешно" },
  th: { failed: "ล้มเหลว", partial: "บางส่วน", skipped: "ข้าม", success: "สำเร็จ" },
  tr: { failed: "başarısız", partial: "kısmi", skipped: "atlandı", success: "başarılı" },
  vi: { failed: "thất bại", partial: "một phần", skipped: "đã bỏ qua", success: "thành công" },
  zh: { failed: "失败", partial: "部分完成", skipped: "已跳过", success: "成功" },
};

const researchLanguageCopy: Record<ResponseLanguageCode, ResearchLanguageCopy> = {
  ar: {
    caveat: "هذه النتيجة بحث اتجاهي ويجب التحقق منها قبل اتخاذ أي قرار.",
    evidenceLabel: "الأدلة",
    found: (topic, count) => `وجد البحث عن "${topic}" ${count} مصدرًا مباشرًا.`,
    limitationLabel: "قيد",
    missing: (topic) => `لم يجد البحث عن "${topic}" أدلة مباشرة كافية.`,
    noProviderIssues: "لم تُسجل أخطاء من مزودي البيانات.",
    onchainLabel: "على السلسلة",
    onchainStatus: (status, count) => `الحالة: ${status}. نتائج الأدوات: ${count}.`,
    providerIssues: (count) => `ظهرت ${count} مشكلة لدى مزودي البيانات.`,
    providers: (value) => `المزودون النشطون: ${value}.`,
    providersLabel: "المزودون",
    recommendation: "راجع المصادر المباشرة وتحقق من أهم الادعاءات قبل استخدامها.",
    retryRecommendation: "أعد البحث بموضوع أكثر تحديدًا وتحقق من إعدادات مزودي البيانات.",
    socialLabel: "الإشارات العامة",
    socialStatus: (status) => `الحالة: ${status}.`,
    synthesisFailed: (reason) => `فشل التلخيص بالذكاء الاصطناعي، لذا استُخدمت نتيجة حتمية.${reason ? ` السبب: ${reason}` : ""}`,
    title: "ملخص البحث",
  },
  de: {
    caveat: "Dieses Ergebnis ist richtungsweisende Recherche und muss vor einer Entscheidung geprüft werden.",
    evidenceLabel: "Evidenz",
    found: (topic, count) => `Die Recherche zu „${topic}“ fand ${count} Live-Quellen.`,
    limitationLabel: "Einschränkung",
    missing: (topic) => `Die Recherche zu „${topic}“ fand nicht genügend Live-Evidenz.`,
    noProviderIssues: "Es wurden keine Anbieterfehler gemeldet.",
    onchainLabel: "On-Chain",
    onchainStatus: (status, count) => `Status: ${status}. Werkzeugergebnisse: ${count}.`,
    providerIssues: (count) => `${count} Anbieterprobleme wurden gemeldet.`,
    providers: (value) => `Aktive Anbieter: ${value}.`,
    providersLabel: "Anbieter",
    recommendation: "Prüfe die Live-Quellen und bestätige die wichtigsten Aussagen vor der Nutzung.",
    retryRecommendation: "Wiederhole die Recherche mit einem engeren Thema und prüfe die Anbieterkonfiguration.",
    socialLabel: "Öffentliche Signale",
    socialStatus: (status) => `Status: ${status}.`,
    synthesisFailed: (reason) => `Die KI-Synthese ist fehlgeschlagen. Eine deterministische Ersatzantwort wurde verwendet.${reason ? ` Grund: ${reason}` : ""}`,
    title: "Rechercheübersicht",
  },
  el: {
    caveat: "Το αποτέλεσμα είναι κατευθυντική έρευνα και χρειάζεται επαλήθευση πριν από οποιαδήποτε απόφαση.",
    evidenceLabel: "Τεκμήρια",
    found: (topic, count) => `Η έρευνα για «${topic}» βρήκε ${count} ζωντανές πηγές.`,
    limitationLabel: "Περιορισμός",
    missing: (topic) => `Η έρευνα για «${topic}» δεν βρήκε αρκετά ζωντανά τεκμήρια.`,
    noProviderIssues: "Δεν αναφέρθηκαν σφάλματα παρόχων.",
    onchainLabel: "On-chain",
    onchainStatus: (status, count) => `Κατάσταση: ${status}. Αποτελέσματα εργαλείων: ${count}.`,
    providerIssues: (count) => `Αναφέρθηκαν ${count} προβλήματα παρόχων.`,
    providers: (value) => `Ενεργοί πάροχοι: ${value}.`,
    providersLabel: "Πάροχοι",
    recommendation: "Έλεγξε τις ζωντανές πηγές και επιβεβαίωσε τους βασικούς ισχυρισμούς πριν από τη χρήση.",
    retryRecommendation: "Επανάλαβε την έρευνα με πιο συγκεκριμένο θέμα και έλεγξε τις ρυθμίσεις παρόχων.",
    socialLabel: "Δημόσια σήματα",
    socialStatus: (status) => `Κατάσταση: ${status}.`,
    synthesisFailed: (reason) => `Η σύνθεση AI απέτυχε και χρησιμοποιήθηκε ντετερμινιστικό αποτέλεσμα.${reason ? ` Αιτία: ${reason}` : ""}`,
    title: "Σύνοψη έρευνας",
  },
  en: {
    caveat: "This result is directional research and must be verified before any decision.",
    evidenceLabel: "Evidence",
    found: (topic, count) => `The research for "${topic}" found ${count} live sources.`,
    limitationLabel: "Caveat",
    missing: (topic) => `The research for "${topic}" did not find enough live evidence.`,
    noProviderIssues: "No provider errors were reported.",
    onchainLabel: "On-chain",
    onchainStatus: (status, count) => `Status: ${status}. Tool results: ${count}.`,
    providerIssues: (count) => `${count} provider issues were reported.`,
    providers: (value) => `Active providers: ${value}.`,
    providersLabel: "Providers",
    recommendation: "Review the live sources and verify the main claims before using the result.",
    retryRecommendation: "Run the research again with a narrower topic and check provider configuration.",
    socialLabel: "Public signals",
    socialStatus: (status) => `Status: ${status}.`,
    synthesisFailed: (reason) => `AI synthesis failed, so a deterministic fallback was used.${reason ? ` Reason: ${reason}` : ""}`,
    title: "Research summary",
  },
  es: {
    caveat: "Este resultado es una investigación orientativa y debe verificarse antes de tomar decisiones.",
    evidenceLabel: "Evidencia",
    found: (topic, count) => `La investigación sobre "${topic}" encontró ${count} fuentes en vivo.`,
    limitationLabel: "Limitación",
    missing: (topic) => `La investigación sobre "${topic}" no encontró suficiente evidencia en vivo.`,
    noProviderIssues: "No se registraron errores de proveedores.",
    onchainLabel: "En cadena",
    onchainStatus: (status, count) => `Estado: ${status}. Resultados de herramientas: ${count}.`,
    providerIssues: (count) => `Se registraron ${count} problemas de proveedores.`,
    providers: (value) => `Proveedores activos: ${value}.`,
    providersLabel: "Proveedores",
    recommendation: "Revisa las fuentes en vivo y verifica las afirmaciones principales antes de usar el resultado.",
    retryRecommendation: "Repite la investigación con un tema más específico y revisa la configuración de proveedores.",
    socialLabel: "Señales públicas",
    socialStatus: (status) => `Estado: ${status}.`,
    synthesisFailed: (reason) => `La síntesis de IA falló y se usó un resultado determinista.${reason ? ` Motivo: ${reason}` : ""}`,
    title: "Resumen de investigación",
  },
  fr: {
    caveat: "Ce résultat est une recherche indicative et doit être vérifié avant toute décision.",
    evidenceLabel: "Preuves",
    found: (topic, count) => `La recherche sur « ${topic} » a trouvé ${count} sources en direct.`,
    limitationLabel: "Limitation",
    missing: (topic) => `La recherche sur « ${topic} » n'a pas trouvé assez de preuves en direct.`,
    noProviderIssues: "Aucune erreur de fournisseur n'a été signalée.",
    onchainLabel: "On-chain",
    onchainStatus: (status, count) => `État : ${status}. Résultats d'outils : ${count}.`,
    providerIssues: (count) => `${count} problèmes de fournisseurs ont été signalés.`,
    providers: (value) => `Fournisseurs actifs : ${value}.`,
    providersLabel: "Fournisseurs",
    recommendation: "Consultez les sources en direct et vérifiez les affirmations principales avant utilisation.",
    retryRecommendation: "Relancez la recherche avec un sujet plus précis et vérifiez la configuration des fournisseurs.",
    socialLabel: "Signaux publics",
    socialStatus: (status) => `État : ${status}.`,
    synthesisFailed: (reason) => `La synthèse par IA a échoué. Un résultat déterministe a été utilisé.${reason ? ` Motif : ${reason}` : ""}`,
    title: "Résumé de recherche",
  },
  he: {
    caveat: "התוצאה היא מחקר כיווני ויש לאמת אותה לפני כל החלטה.",
    evidenceLabel: "ראיות",
    found: (topic, count) => `המחקר על "${topic}" מצא ${count} מקורות חיים.`,
    limitationLabel: "מגבלה",
    missing: (topic) => `המחקר על "${topic}" לא מצא מספיק ראיות חיות.`,
    noProviderIssues: "לא דווחו שגיאות ספקים.",
    onchainLabel: "על השרשרת",
    onchainStatus: (status, count) => `מצב: ${status}. תוצאות כלים: ${count}.`,
    providerIssues: (count) => `דווחו ${count} בעיות ספקים.`,
    providers: (value) => `ספקים פעילים: ${value}.`,
    providersLabel: "ספקים",
    recommendation: "בדוק את המקורות החיים ואמת את הטענות המרכזיות לפני השימוש.",
    retryRecommendation: "הרץ את המחקר שוב עם נושא ממוקד יותר ובדוק את הגדרות הספקים.",
    socialLabel: "אותות ציבוריים",
    socialStatus: (status) => `מצב: ${status}.`,
    synthesisFailed: (reason) => `סינתזת ה-AI נכשלה ולכן נעשה שימוש בתוצאה דטרמיניסטית.${reason ? ` סיבה: ${reason}` : ""}`,
    title: "סיכום מחקר",
  },
  hi: {
    caveat: "यह परिणाम दिशात्मक शोध है। किसी निर्णय से पहले इसकी पुष्टि करें।",
    evidenceLabel: "साक्ष्य",
    found: (topic, count) => `"${topic}" पर शोध में ${count} लाइव स्रोत मिले।`,
    limitationLabel: "सीमा",
    missing: (topic) => `"${topic}" पर शोध में पर्याप्त लाइव साक्ष्य नहीं मिले।`,
    noProviderIssues: "किसी प्रदाता त्रुटि की सूचना नहीं मिली।",
    onchainLabel: "ऑन-चेन",
    onchainStatus: (status, count) => `स्थिति: ${status}। टूल परिणाम: ${count}।`,
    providerIssues: (count) => `${count} प्रदाता समस्याएँ मिलीं।`,
    providers: (value) => `सक्रिय प्रदाता: ${value}।`,
    providersLabel: "प्रदाता",
    recommendation: "नतीजे का उपयोग करने से पहले लाइव स्रोत और मुख्य दावों की पुष्टि करें।",
    retryRecommendation: "अधिक स्पष्ट विषय के साथ शोध दोबारा चलाएँ और प्रदाता सेटिंग जाँचें।",
    socialLabel: "सार्वजनिक संकेत",
    socialStatus: (status) => `स्थिति: ${status}।`,
    synthesisFailed: (reason) => `AI संश्लेषण विफल हुआ, इसलिए निर्धारित fallback इस्तेमाल किया गया।${reason ? ` कारण: ${reason}` : ""}`,
    title: "शोध सारांश",
  },
  id: {
    caveat: "Hasil ini bersifat riset terarah dan harus diverifikasi sebelum mengambil keputusan.",
    evidenceLabel: "Bukti",
    found: (topic, count) => `Riset untuk "${topic}" menemukan ${count} sumber langsung.`,
    limitationLabel: "Keterbatasan",
    missing: (topic) => `Riset untuk "${topic}" belum menemukan bukti langsung yang cukup.`,
    noProviderIssues: "Tidak ada error provider yang tercatat.",
    onchainLabel: "On-chain",
    onchainStatus: (status, count) => `Status: ${status}. Hasil alat: ${count}.`,
    providerIssues: (count) => `Terdapat ${count} masalah provider.`,
    providers: (value) => `Provider aktif: ${value}.`,
    providersLabel: "Provider",
    recommendation: "Tinjau sumber langsung dan verifikasi klaim utama sebelum memakai hasil ini.",
    retryRecommendation: "Jalankan ulang riset dengan topik yang lebih spesifik dan periksa konfigurasi provider.",
    socialLabel: "Sinyal publik",
    socialStatus: (status) => `Status: ${status}.`,
    synthesisFailed: (reason) => `Sintesis AI gagal, sehingga fallback deterministik digunakan.${reason ? ` Alasan: ${reason}` : ""}`,
    title: "Ringkasan riset",
  },
  it: {
    caveat: "Questo risultato è una ricerca indicativa e deve essere verificato prima di ogni decisione.",
    evidenceLabel: "Evidenze",
    found: (topic, count) => `La ricerca su "${topic}" ha trovato ${count} fonti live.`,
    limitationLabel: "Limitazione",
    missing: (topic) => `La ricerca su "${topic}" non ha trovato evidenze live sufficienti.`,
    noProviderIssues: "Non sono stati segnalati errori dei provider.",
    onchainLabel: "On-chain",
    onchainStatus: (status, count) => `Stato: ${status}. Risultati degli strumenti: ${count}.`,
    providerIssues: (count) => `Sono stati segnalati ${count} problemi dei provider.`,
    providers: (value) => `Provider attivi: ${value}.`,
    providersLabel: "Provider",
    recommendation: "Controlla le fonti live e verifica le affermazioni principali prima dell'uso.",
    retryRecommendation: "Ripeti la ricerca con un argomento più specifico e controlla la configurazione dei provider.",
    socialLabel: "Segnali pubblici",
    socialStatus: (status) => `Stato: ${status}.`,
    synthesisFailed: (reason) => `La sintesi AI non è riuscita ed è stato usato un risultato deterministico.${reason ? ` Motivo: ${reason}` : ""}`,
    title: "Riepilogo della ricerca",
  },
  ja: {
    caveat: "この結果は方向性を示す調査です。判断前に検証してください。",
    evidenceLabel: "根拠",
    found: (topic, count) => `「${topic}」の調査で${count}件のライブソースが見つかりました。`,
    limitationLabel: "制限",
    missing: (topic) => `「${topic}」の調査では十分なライブ根拠が見つかりませんでした。`,
    noProviderIssues: "プロバイダーエラーは報告されていません。",
    onchainLabel: "オンチェーン",
    onchainStatus: (status, count) => `状態: ${status}。ツール結果: ${count}件。`,
    providerIssues: (count) => `${count}件のプロバイダー問題が報告されました。`,
    providers: (value) => `有効なプロバイダー: ${value}。`,
    providersLabel: "プロバイダー",
    recommendation: "利用前にライブソースを確認し、主要な主張を検証してください。",
    retryRecommendation: "より具体的なテーマで再調査し、プロバイダー設定を確認してください。",
    socialLabel: "公開シグナル",
    socialStatus: (status) => `状態: ${status}。`,
    synthesisFailed: (reason) => `AI要約に失敗したため、決定論的な代替結果を使用しました。${reason ? ` 理由: ${reason}` : ""}`,
    title: "調査概要",
  },
  ko: {
    caveat: "이 결과는 방향성 연구이며 결정을 내리기 전에 검증해야 합니다.",
    evidenceLabel: "근거",
    found: (topic, count) => `"${topic}" 연구에서 ${count}개의 실시간 출처를 찾았습니다.`,
    limitationLabel: "제한",
    missing: (topic) => `"${topic}" 연구에서 충분한 실시간 근거를 찾지 못했습니다.`,
    noProviderIssues: "제공자 오류가 보고되지 않았습니다.",
    onchainLabel: "온체인",
    onchainStatus: (status, count) => `상태: ${status}. 도구 결과: ${count}개.`,
    providerIssues: (count) => `${count}개의 제공자 문제가 보고되었습니다.`,
    providers: (value) => `활성 제공자: ${value}.`,
    providersLabel: "제공자",
    recommendation: "사용하기 전에 실시간 출처와 주요 주장을 검증하세요.",
    retryRecommendation: "더 구체적인 주제로 다시 조사하고 제공자 설정을 확인하세요.",
    socialLabel: "공개 신호",
    socialStatus: (status) => `상태: ${status}.`,
    synthesisFailed: (reason) => `AI 종합에 실패하여 결정론적 대체 결과를 사용했습니다.${reason ? ` 이유: ${reason}` : ""}`,
    title: "연구 요약",
  },
  nl: {
    caveat: "Dit resultaat is richtinggevend onderzoek en moet voor elke beslissing worden geverifieerd.",
    evidenceLabel: "Bewijs",
    found: (topic, count) => `Het onderzoek naar "${topic}" vond ${count} live bronnen.`,
    limitationLabel: "Beperking",
    missing: (topic) => `Het onderzoek naar "${topic}" vond onvoldoende live bewijs.`,
    noProviderIssues: "Er zijn geen providerfouten gemeld.",
    onchainLabel: "On-chain",
    onchainStatus: (status, count) => `Status: ${status}. Toolresultaten: ${count}.`,
    providerIssues: (count) => `${count} providerproblemen zijn gemeld.`,
    providers: (value) => `Actieve providers: ${value}.`,
    providersLabel: "Providers",
    recommendation: "Controleer de live bronnen en verifieer de belangrijkste claims voor gebruik.",
    retryRecommendation: "Voer het onderzoek opnieuw uit met een specifieker onderwerp en controleer de providerconfiguratie.",
    socialLabel: "Publieke signalen",
    socialStatus: (status) => `Status: ${status}.`,
    synthesisFailed: (reason) => `AI-synthese is mislukt. Een deterministisch alternatief is gebruikt.${reason ? ` Reden: ${reason}` : ""}`,
    title: "Onderzoekssamenvatting",
  },
  pt: {
    caveat: "Este resultado é uma pesquisa direcional e deve ser verificado antes de qualquer decisão.",
    evidenceLabel: "Evidência",
    found: (topic, count) => `A pesquisa sobre "${topic}" encontrou ${count} fontes ao vivo.`,
    limitationLabel: "Limitação",
    missing: (topic) => `A pesquisa sobre "${topic}" não encontrou evidência ao vivo suficiente.`,
    noProviderIssues: "Nenhum erro de provedor foi relatado.",
    onchainLabel: "On-chain",
    onchainStatus: (status, count) => `Status: ${status}. Resultados de ferramentas: ${count}.`,
    providerIssues: (count) => `${count} problemas de provedores foram relatados.`,
    providers: (value) => `Provedores ativos: ${value}.`,
    providersLabel: "Provedores",
    recommendation: "Revise as fontes ao vivo e confirme as principais afirmações antes do uso.",
    retryRecommendation: "Execute a pesquisa novamente com um tema mais específico e confira a configuração dos provedores.",
    socialLabel: "Sinais públicos",
    socialStatus: (status) => `Status: ${status}.`,
    synthesisFailed: (reason) => `A síntese de IA falhou e um resultado determinístico foi usado.${reason ? ` Motivo: ${reason}` : ""}`,
    title: "Resumo da pesquisa",
  },
  ru: {
    caveat: "Этот результат является ориентировочным исследованием и требует проверки перед любым решением.",
    evidenceLabel: "Доказательства",
    found: (topic, count) => `Исследование по теме «${topic}» нашло ${count} актуальных источников.`,
    limitationLabel: "Ограничение",
    missing: (topic) => `Исследование по теме «${topic}» не нашло достаточно актуальных доказательств.`,
    noProviderIssues: "Ошибки поставщиков данных не зарегистрированы.",
    onchainLabel: "Ончейн",
    onchainStatus: (status, count) => `Статус: ${status}. Результаты инструментов: ${count}.`,
    providerIssues: (count) => `Зарегистрировано проблем поставщиков: ${count}.`,
    providers: (value) => `Активные поставщики: ${value}.`,
    providersLabel: "Поставщики",
    recommendation: "Проверьте актуальные источники и основные утверждения перед использованием.",
    retryRecommendation: "Повторите исследование с более узкой темой и проверьте настройки поставщиков.",
    socialLabel: "Публичные сигналы",
    socialStatus: (status) => `Статус: ${status}.`,
    synthesisFailed: (reason) => `Синтез ИИ завершился ошибкой, поэтому использован детерминированный результат.${reason ? ` Причина: ${reason}` : ""}`,
    title: "Сводка исследования",
  },
  th: {
    caveat: "ผลลัพธ์นี้เป็นงานวิจัยเชิงทิศทางและต้องตรวจสอบก่อนตัดสินใจ",
    evidenceLabel: "หลักฐาน",
    found: (topic, count) => `การวิจัยเรื่อง "${topic}" พบแหล่งข้อมูลสด ${count} แหล่ง`,
    limitationLabel: "ข้อจำกัด",
    missing: (topic) => `การวิจัยเรื่อง "${topic}" ไม่พบหลักฐานสดที่เพียงพอ`,
    noProviderIssues: "ไม่พบข้อผิดพลาดจากผู้ให้บริการ",
    onchainLabel: "ออนเชน",
    onchainStatus: (status, count) => `สถานะ: ${status} ผลลัพธ์เครื่องมือ: ${count}`,
    providerIssues: (count) => `พบปัญหาผู้ให้บริการ ${count} รายการ`,
    providers: (value) => `ผู้ให้บริการที่ใช้งาน: ${value}`,
    providersLabel: "ผู้ให้บริการ",
    recommendation: "ตรวจสอบแหล่งข้อมูลสดและยืนยันข้ออ้างหลักก่อนใช้งาน",
    retryRecommendation: "เรียกงานวิจัยใหม่ด้วยหัวข้อที่เฉพาะเจาะจงขึ้นและตรวจสอบการตั้งค่าผู้ให้บริการ",
    socialLabel: "สัญญาณสาธารณะ",
    socialStatus: (status) => `สถานะ: ${status}`,
    synthesisFailed: (reason) => `การสังเคราะห์ AI ล้มเหลว จึงใช้ผลลัพธ์สำรองแบบกำหนดตายตัว${reason ? ` เหตุผล: ${reason}` : ""}`,
    title: "สรุปงานวิจัย",
  },
  tr: {
    caveat: "Bu sonuç yön gösteren bir araştırmadır ve karar öncesinde doğrulanmalıdır.",
    evidenceLabel: "Kanıt",
    found: (topic, count) => `"${topic}" araştırması ${count} canlı kaynak buldu.`,
    limitationLabel: "Sınırlama",
    missing: (topic) => `"${topic}" araştırması yeterli canlı kanıt bulamadı.`,
    noProviderIssues: "Sağlayıcı hatası bildirilmedi.",
    onchainLabel: "Zincir üstü",
    onchainStatus: (status, count) => `Durum: ${status}. Araç sonuçları: ${count}.`,
    providerIssues: (count) => `${count} sağlayıcı sorunu bildirildi.`,
    providers: (value) => `Etkin sağlayıcılar: ${value}.`,
    providersLabel: "Sağlayıcılar",
    recommendation: "Kullanmadan önce canlı kaynakları ve temel iddiaları doğrulayın.",
    retryRecommendation: "Araştırmayı daha dar bir konuyla yeniden çalıştırın ve sağlayıcı ayarlarını kontrol edin.",
    socialLabel: "Herkese açık sinyaller",
    socialStatus: (status) => `Durum: ${status}.`,
    synthesisFailed: (reason) => `AI sentezi başarısız oldu ve belirlenmiş yedek sonuç kullanıldı.${reason ? ` Neden: ${reason}` : ""}`,
    title: "Araştırma özeti",
  },
  vi: {
    caveat: "Kết quả này là nghiên cứu định hướng và cần được xác minh trước khi ra quyết định.",
    evidenceLabel: "Bằng chứng",
    found: (topic, count) => `Nghiên cứu về "${topic}" đã tìm thấy ${count} nguồn trực tiếp.`,
    limitationLabel: "Giới hạn",
    missing: (topic) => `Nghiên cứu về "${topic}" chưa tìm thấy đủ bằng chứng trực tiếp.`,
    noProviderIssues: "Không ghi nhận lỗi nhà cung cấp.",
    onchainLabel: "On-chain",
    onchainStatus: (status, count) => `Trạng thái: ${status}. Kết quả công cụ: ${count}.`,
    providerIssues: (count) => `Ghi nhận ${count} vấn đề từ nhà cung cấp.`,
    providers: (value) => `Nhà cung cấp đang hoạt động: ${value}.`,
    providersLabel: "Nhà cung cấp",
    recommendation: "Hãy kiểm tra nguồn trực tiếp và xác minh các nhận định chính trước khi sử dụng.",
    retryRecommendation: "Chạy lại nghiên cứu với chủ đề cụ thể hơn và kiểm tra cấu hình nhà cung cấp.",
    socialLabel: "Tín hiệu công khai",
    socialStatus: (status) => `Trạng thái: ${status}.`,
    synthesisFailed: (reason) => `Tổng hợp AI thất bại nên hệ thống dùng kết quả dự phòng xác định.${reason ? ` Lý do: ${reason}` : ""}`,
    title: "Tóm tắt nghiên cứu",
  },
  zh: {
    caveat: "该结果仅用于方向性研究，作出任何决定前都应核实。",
    evidenceLabel: "证据",
    found: (topic, count) => `关于“${topic}”的研究找到 ${count} 个实时来源。`,
    limitationLabel: "限制",
    missing: (topic) => `关于“${topic}”的研究未找到足够的实时证据。`,
    noProviderIssues: "未报告数据提供方错误。",
    onchainLabel: "链上",
    onchainStatus: (status, count) => `状态：${status}。工具结果：${count}。`,
    providerIssues: (count) => `报告了 ${count} 个数据提供方问题。`,
    providers: (value) => `活跃数据提供方：${value}。`,
    providersLabel: "数据提供方",
    recommendation: "使用结果前，请检查实时来源并核实主要结论。",
    retryRecommendation: "请使用更具体的主题重新研究，并检查数据提供方配置。",
    socialLabel: "公开信号",
    socialStatus: (status) => `状态：${status}。`,
    synthesisFailed: (reason) => `AI 综合失败，因此使用了确定性备用结果。${reason ? ` 原因：${reason}` : ""}`,
    title: "研究摘要",
  },
};
